#!/usr/bin/julia

include("lib/Neuron.jl")

network =
    Neuron.Network([
        Neuron.Layer(2),
        Neuron.Layer(2),
        Neuron.Layer(1),
    ])

# all possible xor combinations
dataset = [
    [[0, 0], [0]],
    [[0, 1], [1]],
    [[1, 0], [1]],
    [[1, 1], [0]],
]

Neuron.train(network, dataset)

input = convert(Vector{Float64}, [parse(Int64, ARGS[1]), parse(Int64, ARGS[2])])
result = Neuron.predict(network, input)
println(Int64(round(result[1])))
