#!/usr/bin/julia

include("lib/Neuron.jl")
include("lib/Math.jl")

input_neurons_len = 8
input_neurons = rand(Float64, input_neurons_len) * 2 .- 1

neural_net =
    Neuron.Network([
        Neuron.Layer(input_neurons),
        Neuron.Layer(input_neurons_len * 2),
        Neuron.Layer(input_neurons_len * 2),
        Neuron.Layer(input_neurons_len * 2),
        Neuron.Layer(input_neurons_len * 2),
        Neuron.Layer(input_neurons_len ÷ 2),
    ])

Neuron.randomize_weights(neural_net)

Neuron.forward_prop(neural_net, Math.sigmoid)
loss = Neuron.loss(neural_net, [1, 0, 0, 0])
println("Loss: $loss")
